import 'dart:convert';
import 'dart:io';

import 'package:dio/dio.dart';
import 'package:pretty_dio_logger/pretty_dio_logger.dart';

/// The main WooCommerce API client class that provides access to all WooCommerce REST API endpoints.
///
/// This class serves as the central entry point for interacting with WooCommerce stores.
/// It handles authentication, HTTP requests, and provides extensions for different API modules
/// like products, orders, customers, etc.
///
/// ## Basic Usage
///
/// ```dart
/// final woocommerce = WooCommerce(
///   baseUrl: 'https://yourstore.com',
///   username: 'ck_your_consumer_key',
///   password: 'cs_your_consumer_secret',
/// );
///
/// // Fetch products
/// final products = await woocommerce.getProducts();
/// ```
///
/// ## Development Mode
///
/// For development and testing, you can enable fake data mode:
///
/// ```dart
/// final woocommerce = WooCommerce(
///   baseUrl: 'https://yourstore.com',
///   username: 'ck_your_consumer_key',
///   password: 'cs_your_consumer_secret',
///   useFaker: true, // Returns fake data instead of making real API calls
/// );
/// ```
///
/// ## Custom API Calls
///
/// If you need to call endpoints not yet implemented by this package,
/// you can use the exposed [dio] instance:
///
/// ```dart
/// final response = await woocommerce.dio.get('/custom-endpoint');
/// ```
class WooCommerce {
  /// The Dio HTTP client instance used for making API requests.
  ///
  /// This instance is pre-configured with authentication headers and base URL.
  /// You can use it directly for custom API calls or add additional interceptors.
  late final Dio dio;

  /// The base URL of your WooCommerce store.
  ///
  /// Should include the protocol (http:// or https://) and domain.
  /// Example: 'https://yourstore.com' or 'http://localhost:8080'
  final String baseUrl;

  /// The consumer key for WooCommerce REST API authentication.
  ///
  /// This is the "Consumer Key" from your WooCommerce REST API settings.
  /// Example: 'ck_12abc34n56j789xyz'
  final String username;

  /// The consumer secret for WooCommerce REST API authentication.
  ///
  /// This is the "Consumer Secret" from your WooCommerce REST API settings.
  /// Example: 'cs_1uab8h3s3op456def'
  final String password;

  /// Custom API path for WooCommerce REST API.
  ///
  /// Defaults to '/wp-json/wc/v3'. Only change this if your WooCommerce
  /// installation uses a different API path.
  final String? apiPath;

  /// Whether to enable debug logging for HTTP requests.
  ///
  /// When true, all HTTP requests and responses will be logged to the console.
  /// Useful for development and debugging.
  final bool isDebug;

  /// Whether to use fake data instead of making real API calls.
  ///
  /// When true, all API methods will return fake data generated by the faker package.
  /// This is useful for development when you don't have a live WooCommerce store
  /// or want to test your app without affecting real data.
  final bool useFaker;

  /// Creates a new WooCommerce API client instance.
  ///
  /// ## Required Parameters
  ///
  /// - [baseUrl]: The base URL of your WooCommerce store (e.g., 'https://yourstore.com')
  /// - [username]: Your WooCommerce REST API consumer key (e.g., 'ck_12abc34n56j')
  /// - [password]: Your WooCommerce REST API consumer secret (e.g., 'cs_1uab8h3s3op')
  ///
  /// ## Optional Parameters
  ///
  /// - [apiPath]: Custom API path (defaults to '/wp-json/wc/v3')
  /// - [isDebug]: Enable debug logging (defaults to true)
  /// - [useFaker]: Use fake data for development (defaults to false)
  /// - [interceptors]: Additional Dio interceptors for custom functionality
  ///
  /// ## Example
  ///
  /// ```dart
  /// final woocommerce = WooCommerce(
  ///   baseUrl: 'https://yourstore.com',
  ///   username: 'ck_your_consumer_key',
  ///   password: 'cs_your_consumer_secret',
  ///   isDebug: true,
  ///   useFaker: false,
  /// );
  /// ```
  WooCommerce({
    required this.baseUrl,
    required this.username,
    required this.password,
    this.apiPath = '/wp-json/wc/v3',
    this.isDebug = true,
    this.useFaker = false,
    List<Interceptor>? interceptors,
  }) {
    final authToken = base64.encode(utf8.encode('$username:$password'));
    dio = Dio(
      BaseOptions(
        baseUrl: '$baseUrl$apiPath',
        headers: {
          HttpHeaders.authorizationHeader: 'Basic $authToken',
        },
      ),
    );

    if (isDebug) {
      dio.interceptors.add(PrettyDioLogger(
        requestHeader: true,
        requestBody: true,
        responseBody: true,
      ));
    }

    if (interceptors != null) dio.interceptors.addAll(interceptors);
  }
}
